server:
  port: 8880

# mybatis配置
# 增加数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wiki?characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 9264946
    driver-class-name: com.mysql.jdbc.Driver

# 配置mybatis所有Mapper.xml所在的路径
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

# 自定义配置项
test:
  hello: hello