server:
  port: 8880

# mybatis配置
# 增加数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wiki?characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 9264946
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:

# 配置mybatis所有Mapper.xml所在的路径
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

# rocketmq配置
#rocketmq:
#  name-server: 127.0.0.1:9876
#  # 分组名称
#  producer:
#    group: default

# 打印所有sql日志：sql，参数，结果
logging:
  level:
    com:
      wx:
        wiki:
          mapper: trace


# 自定义配置项
test:
  hello: hello